### ISSUE TITLE
Missing config in /store/actions.js

### ISSUE THREAD

**Issue by sleleko** [jtzook/pnw-trees#1]
Hello!
When I,m try to run your component, I'll give a error about missing config 

In /store/action.js  I,m see import config from "../../config/config"; but this config does't exists.

**Comment by jtzook** [comment]
Hi There!

This is config file is not included in the repo as it holds my API key for the flickr API that the app relies on. It is called `config/config.js` and contains the following:

```
// flikr api
export default {
  api_key: "<flickr API key>",
};
```

You may get your own free API key at flickr by 'creating an app' [here](https://www.flickr.com/services/apps/create/) or by adapting the `fetchTrees` action to a different image-fetching API.
